deployUrl=file:///Users/cer/.m2/testdeploy

eventuateMavenRepoUrl=file:///Users/cer/.m2/testdeploy,https://snapshots.repositories.eventuate.io/repository

eventuatePluginsGradleVersion=0.15.0.BUILD-SNAPSHOT
springBootVersion=4.1.1
micrometerTracingVersion=1.7.1
micrometerVersion=1.17.1
testContainersVersion=2.0.5
jacksonVersion=3.1.5
slf4jVersion=2.0.18
junitVersion=6.0.3
mockitoVersion=5.23.0
assertjVersion=3.27.7
braveVersion=6.3.1
zipkinReporterVersion=3.5.3
openTelemetryVersion=1.62.0

eventuateUtilVersion=0.20.0.BUILD-SNAPSHOT

eventuateTramVersion=0.38.0.BUILD-SNAPSHOT

eventuateCommonImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateMessagingKafkaImageVersion=0.22.0.BUILD-SNAPSHOT
eventuateCdcImageVersion=0.20.0.BUILD-SNAPSHOT
eventuateCdcKafkaEnableBatchProcessing=false

versionProperty=eventuateTramSpringMicrometerTracingVersion
version=0.2.0-SNAPSHOT
